import type { ReadonlyArray } from "@coven/types";
import type { RecursiveMap } from "./RecursiveMap.ts";
import { ROOT_SYMBOL } from "./ROOT_SYMBOL.ts";

/**
 * Gets values generated by `mapSetRecursive`.
 *
 * @internal
 * @param map Map to be mutated.
 * @param array Array of nested keys.
 */
export const mapGetRecursive = (
	map: Map<unknown, unknown>,
	array: ReadonlyArray,
): unknown =>
	array.reduce<RecursiveMap>(
		(currentMap, item) => currentMap?.get(item) as RecursiveMap,
		map as RecursiveMap,
	)?.get(ROOT_SYMBOL) as unknown;
