import { EMPTY_OBJECT } from "@coven/constants";
import { memo } from "@coven/memo";
import type {
	ExpectedStringables,
	ReadonlyRecord,
	RegularExpressionFlags,
	Stringable,
} from "@coven/types";

/**
 * @internal Small type to work with {@linkcode ExpectedStringables} to add
 * the expected parts of a group name to the given strings.
 */
export type WrapGroupKeys<GroupKeys extends ReadonlyArray<Stringable>> =
	GroupKeys extends (
		readonly [
			infer Head extends Stringable,
			...infer Tail extends ReadonlyArray<Stringable>,
		]
	) ?
		readonly [`(?<${Head}>`, ...WrapGroupKeys<Tail>]
	:	ReadonlyArray<never>;

/**
 * Given a regular expression (ideally generated by `@coven/expression`'s `build`
 * or `buildUnicode`), extract only the groups on it.
 *
 * @example Escape given value
 * ```typescript
 * import { buildUnicode, captureNamed, WILDCARD } from "@coven/expression";
 *
 * const getExample = getGroups<readonly ["example"]>(
 * 	buildUnicode(captureNamed("example")(WILDCARD)) // /(?<example>.)/
 * );
 *
 * getExample("🔮"); // { example: "🔮" }
 * ```
 * @param escaped Value to escape.
 * @returns Escaped value.
 */
export const getGroups =
	<GroupKeys extends ReadonlyArray<Stringable>>({
		flags,
		source,
	}: {
		flags: RegularExpressionFlags;
		source: ExpectedStringables<WrapGroupKeys<GroupKeys>>;
	}): ((
		stringable: Stringable,
	) => Partial<ReadonlyRecord<`${GroupKeys[number]}`, string>>) =>
	(stringable) =>
		memo(
			new RegExp(source, flags).exec(`${stringable}`)?.groups
				?? EMPTY_OBJECT,
		) as ReadonlyRecord<`${GroupKeys[number]}`, string>;
